### ISSUE TITLE
API call not working for Altmetric

### ISSUE THREAD

**Issue by cpunj** [eprintsug/altmetric#11]
$c->{altmetric}->{base_url} = "https://api.altmetric.com/v1";

API call to https://api.altmetric.com/v1 responds with Cannot get /v1

**Comment by goetzk** [comment]
Does it work with a trailing slash?

https://api.altmetric.com/v1/

**Comment by cpunj** [comment]
Hi Karl,

No, it gives the same error. 

Cannot GET /v1/

**Comment by jesusbagpuss** [comment]
You have to provide some parameters e.g.

https://api.altmetric.com/v1/doi/10.1038/480426a

If you go to https://api.altmetric.com/ (without 'v1') it will give you details of the parameters required.
________________________________

**Comment by cpunj** [comment]
Thank you for providing the link to altmetric website. I had a look at it and yes, the specific calls do work. But what I was confused about is the API link in- 
/cfg/cfg.d/z_altmetric.pl 

The file has-
# Altmetric API URL
$c->{altmetric}->{base_url} = "https://api.altmetric.com/v1";

And our **ePrints** repo has started showing an error loading the statistics since last week. So, I was thinking that the API URL above might be causing it.

**Comment by jesusbagpuss** [comment]
Hi @cpunj,
Is the error this one: https://github.com/eprintsug/altmetric/issues/7 ?

If so, does this addition:
https://github.com/eprintsug/altmetric/blob/iss-7/cgi/altmetric#L14
fix it?

**Comment by cpunj** [comment]
Hi John,

I will give it a try and will let you know. 

Thank you

**Comment by cpunj** [comment]
Hi John,

I tried the suggested fix but it is still not working for us.

Thank you 

CP

**Comment by jesusbagpuss** [comment]
Hi CP,
What it the error message that is displayed?
Is your EPrints system public? Can you send me a link to an example?

**Comment by cpunj** [comment]
Hi John,

The error message is- "An error has occurred whilst retrieving data from Altmetric."

Yes, our ePrints is public and you can see this example below-

https://eprints.utas.edu.au/32638/

Thanks
CP

**Comment by jesusbagpuss** [comment]
Hi CP,
Probably worth following this up via email.
Can you drop me a line at j.salter@leeds.ac.uk and I'll see if I can help you!

**Comment by jesusbagpuss** [comment]
Following a bit more debugging, it was discovered that the `$c->{altmetric}->{base_url}` setting had a trailing slash.
This resulted in the call to the Altmetric API having a doubled-slash in it:  `https://api.altmetric.com/v1//doi/10.1103/PhysRevD.101.084002` 
which was producing the error.

Thanks @cpunj for getting in contact - glad we managed to trace it!
