### ISSUE TITLE
Altmetric box not displaying on HTTPS

### ISSUE THREAD

**Issue by Monica-Wood** [eprintsug/altmetric#3]
the line in the Altmetrics.pm 

return 0 if $self->{session}->get_secure;  

Means the altmetrics box will not display on any https pages (or pages that were rendered/generated over https).

this line was found to work to keep the Box out of the preview screen:
return 0 if $self->{session}->is_online && $self->{session}->param("screen") eq "EPrint::View";

See the Mailing list for discussion based on this:
http://mailman.ecs.soton.ac.uk/pipermail/eprints-tech/2018-February/007179.html

Monica

**Comment by jesusbagpuss** [comment]
I think this actioned by: https://github.com/eprintsug/altmetric/commit/eeaa5cc9389be589c9cb7725f2e062d53aa0a3c0.
