### ISSUE TITLE
Altmetric box displays without contents

### ISSUE THREAD

**Issue by drn05r** [eprintsug/altmetric#6]
Displaying the Altmetric box but with no contents because there is no DOI (doi or id_number field) or ISBN (isbn field) value is not very user-friendly.  Repository admins may assume something must have gone wrong, whereas there is just no data to be displayed.  Either the box should not be  visible (i.e. can_be_viewed returns 0) if there is nothing is returned by `$c->{altmetric}->{get_type_and_id}` or there should be some message, different from when the JavaScript Altmetric lookup finds no data, to indicate why no data is being displayed in the Altmetric box.

**Comment by jesusbagpuss** [comment]
Sounds reasonable!
I'll take a look at this, and review the API documentation to see if there have been any changes that should be included in a v3.
