### ISSUE TITLE
Altmetric blocking libwww-perl user agent strings

### ISSUE THREAD

**Issue by drn05r** [eprintsug/altmetric#7]
I have noticed that on several repository the Altmetric box is returning:

> An error has occured whilst retrieving data from Altmetric.

Further investigation finds that this is due to using the user agent string libwww-perl/VERSION.  I have added the following to cgi/altmetric the line after the $ua is instantiated and this seems to fix the issue:

$ua->agent( 'eprints/' . EPrints->human_version );

**Comment by drn05r** [comment]
P.S. In the process of debugging this I noticed the z_altmetric.pl still uses an HTTP rather than HTTPS API URL.  This looks to get redirected without issue but I updated this just in case during my debugging.  I think it may be worth updating it in the packaged z_altmetric.pl.

**Comment by jesusbagpuss** [comment]
Looks like we've both been investigating the same thing!
The above correlates with what I discovered too. I've asked the Altmetric Support people if a bit more info too.

**Comment by jesusbagpuss** [comment]
Support ticket with Altmetric: https://help.altmetric.com/support/tickets/401411

**Comment by yurj** [comment]
Still an issue?

**Comment by jesusbagpuss** [comment]
Hi @yurj,
The 'user agent' fix suggested here works.

Are you in a position to test the following package?
https://github.com/jesusbagpuss/altmetric/blob/autobuild-epm/altmetric.epm

This has been automatically built using GitHub actions, and contains a few other improvements.
If it is OK, I'll merge my fork back into eprintsug version and upload to the Bazaar.

**Comment by yurj** [comment]
I'm not using the plugin, just investigating if It can work if used. But I can test it in a Eprint test instance to see if it works. Maybe @drn05r did it already.

**Comment by drn05r** [comment]
Sorry it has taken a while but confirm I am happy with this fix.
